# Generated by Django 5.2.4 on 2025-07-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qruser',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes_img/'),
        ),
    ]
