# Generated by Django 5.2.4 on 2025-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_alter_qruser_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qruser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qruser',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qruser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
